### ISSUE TITLE
Analysis LDR instruction Error

### ISSUE THREAD

**Issue by IIIImmmyyy** [SamboyCoding/Disarm#23]
88 06 42 F8                   LDR             X8, [X20],#0x20  this is in IDA；
Disarm is out this instruction to string is right,
 but when i try to get op1 it's [X20+32]  and op2 is NONE ,  op1 must be [X20] op2 is Immediate

**Comment by SamboyCoding** [comment]
In this case, `Op0Kind` would be `Register`, `Op0Reg` would be X8, `Op1Kind` would be `Memory`, `MemBase` would be X20, and `MemOffset` would be 32.

The `[X20], #0x20` syntax is just the post-indexed memory access syntax, it's not actually a separate operand.
